- name: Install dependencies for kubectl
  apt:
    name:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg
    state: present

- name: Add Kubernetes GPG key
  apt_key:
    url: https://pkgs.k8s.io/core:/stable:/v1.29/deb/Release.key
    state: present

- name: Add Kubernetes repository
  apt_repository:
    repo: "deb https://pkgs.k8s.io/core:/stable:/v1.29/deb/ /"
    state: present
    filename: kubernetes

- name: Update package index
  apt:
    update_cache: yes

- name: Install kubectl
  apt:
    name: kubectl
    state: present

- name: Configure kubectl aliases
  blockinfile:
    path: /etc/bash.bashrc
    block: |
      source <(kubectl completion bash)
      alias k=kubectl
      complete -F __start_kubectl k
    marker: "#<!-- {mark} ANSIBLE MANAGED BLOCK -->"
    state: present

